# Generated by Django 5.2.3 on 2025-07-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='term',
            field=models.IntegerField(choices=[(12, '12 meses'), (24, '24 meses'), (36, '36 meses'), (48, '48 meses')]),
        ),
    ]
