# Generated by Django 5.2.3 on 2025-07-23 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='reference_number',
        ),
    ]
