# Generated by Django 5.2.3 on 2025-07-23 17:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reference_number',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
