# Generated by Django 5.2.3 on 2025-07-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='document_number',
            field=models.CharField(max_length=20),
        ),
    ]
