# Generated by Django 5.2.3 on 2025-07-23 16:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del objetivo')),
                ('category', models.CharField(choices=[('VACACIONES', 'Vacaciones'), ('AUTO', 'Nuevo auto'), ('EMERGENCIA', 'Fondo de emergencia'), ('CASA', 'Casa'), ('EDUCACION', 'Educación'), ('SALUD', 'Salud'), ('OTRO', 'Otro')], max_length=20, verbose_name='Categoría')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Meta de ahorro')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Cantidad actual')),
                ('target_date', models.DateField(verbose_name='Fecha objetivo')),
                ('status', models.CharField(choices=[('ACTIVO', 'Activo'), ('COMPLETADO', 'Completado'), ('PAUSADO', 'Pausado'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'savings_goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Depósito'), ('WITHDRAWAL', 'Retiro')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'savings_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
