# Generated by Django 5.2.3 on 2025-07-29 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Depósito'), ('WITHDRAWAL', 'Retiro'), ('TRANSFER_SENT', 'Transferencia enviada'), ('TRANSFER_RECEIVED', 'Transferencia recibida'), ('PAYMENT', 'Pago'), ('REFUND', 'Reembolso'), ('CREDIT_DEPOSIT', 'Depósito de crédito'), ('CREDIT_PAYMENT', 'Pago de crédito'), ('SAVINGS_DEPOSIT', 'Depósito a objetivo de ahorro'), ('SAVINGS_WITHDRAWAL', 'Retiro de objetivo de ahorro'), ('SAVINGS_RETURN', 'Devolución de fondos de objetivo'), ('APORT', 'Aporte')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completada'), ('FAILED', 'Fallida'), ('CANCELLED', 'Cancelada')], default='COMPLETED', max_length=20)),
                ('reference_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
