# Generated by Django 5.2.3 on 2025-07-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Depósito'), ('WITHDRAWAL', 'Retiro'), ('TRANSFER_SENT', 'Transferencia enviada'), ('TRANSFER_RECEIVED', 'Transferencia recibida'), ('PAYMENT', 'Pago'), ('REFUND', 'Reembolso'), ('CREDIT_DEPOSIT', 'Depósito de crédito'), ('CREDIT_PAYMENT', 'Pago de crédito'), ('SAVINGS_DEPOSIT', 'Depósito a objetivo de ahorro'), ('SAVINGS_WITHDRAWAL', 'Retiro de objetivo de ahorro'), ('SAVINGS_RETURN', 'Devolución de fondos de objetivo')], max_length=20),
        ),
    ]
